name: rf_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel=6.28.0
  - lightgbm=4.6.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - shap=0.47.1
  - xlrd=2.0.1
  - imbalanced-learn=0.12.2
  - seaborn=0.13.2
